# Generated by Django 3.2.11 on 2022-01-08 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=700)),
                ('id_pokedex', models.IntegerField()),
                ('description', models.TextField()),
                ('id_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='element_pokemons', to='api.element')),
            ],
        ),
    ]
